config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	get 'welcome/about', to: 'welcome#about'

	resources  :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length:{minimum:3 , maximum:50}
	validates :description, presence: true, length:{minimum:3 , maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash[:notice] = "Article is deleted"
		redirect_to articles_path
	end

	def create
		@article =Article.new(article_params)
		if @article.save
			flash[:notice] = "Article was created successfully"
			redirect_to article_path(@article) #redirect to the show 
		else
			render 'new' #else new form empty wala is displayed
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:notice] = "Article is updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	private
	def article_params
		params.require(:article).permit(:title, :description)
	end

	def articles_show

	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index	
	end
	
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>Errors! Empty submission made</h2>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
	</ul>
<% end %> 

<%= form_for @article do |f| %>
	<p>
		<%= f.label :title  %><br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</p>
		<%= f.submit %>
	<p>
	</p>
<% end %>

<%= link_to 'Articles',articles_path %>

app/views/articles/edit.html.erb
<h1>Edit the article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<H1>This is the index page showing all articles</H1>
<p><%= link_to 'Create new Article',new_article_path %></p>
<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
		<td><%= article.title %></td>
		<td><%= article.description %></td>
		<td><%= link_to 'Edit',edit_article_path(article) %></td>
		<td><%= link_to 'Show',article_path(article) %></td>
		<td><%= link_to 'Delete',article_path(article),method: :delete,data: {confirm: "Are you sure to delete this?"} %></td>
	</tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1> Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>
	<b>Title:</b> <%= @article.title %>
</p>

<p>
	<b>Description:</b> <%= @article.description %>
</p>

<%= link_to 'View All Articles',articles_path %><br>
<%= link_to 'Edit Article',edit_article_path(@article) %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
<ul>
    <li><%= msg %></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>This is the about page of the blog</h1>

<%= link_to 'Home',root_path %>

app/views/welcome/index.html.erb
<h1> This is my course sample blog</h1>

<%= link_to 'About',welcome_about_path %>

<%= link_to 'Articles',articles_path %>